//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightHouseMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent_Profile
    {
        public int CNIC_No { get; set; }
        public string Username { get; set; }
        public string Email_ID { get; set; }
        public string Password_MD5 { get; set; }
        public int School_ID { get; set; }
        public string School_Name { get; set; }
        public string Phone_No { get; set; }
        public string Registered_Kids { get; set; }
        public string Postal_Address { get; set; }
    
        public virtual School_Profile School_Profile { get; set; }
    }
}
