//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightHouseMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Profile
    {
        public School_Profile()
        {
            this.Parent_Profile = new HashSet<Parent_Profile>();
            this.Student_Profile = new HashSet<Student_Profile>();
            this.Teacher_Profile = new HashSet<Teacher_Profile>();
        }
    
        public int School_ID { get; set; }
        public string SchoolAdmin_username { get; set; }
        public string School_Name { get; set; }
        public string Password_MD5 { get; set; }
        public string School_Branches { get; set; }
        public string Phone_No { get; set; }
        public string CNIC_No { get; set; }
        public string School_Type { get; set; }
        public string Teachers { get; set; }
        public string Class_Rooms { get; set; }
        public string Students { get; set; }
        public string Postal_Address { get; set; }
    
        public virtual ICollection<Parent_Profile> Parent_Profile { get; set; }
        public virtual ICollection<Student_Profile> Student_Profile { get; set; }
        public virtual ICollection<Teacher_Profile> Teacher_Profile { get; set; }
    }
}
