//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightHouseMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Profile
    {
        public int Student_ID { get; set; }
        public int School_ID { get; set; }
        public string Name { get; set; }
        public byte[] Picture { get; set; }
        public string School_Roll_Number { get; set; }
        public string NFC_Student_ID { get; set; }
        public string Subjects { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public int Parent_CNIC { get; set; }
        public string Parent_Name { get; set; }
    
        public virtual School_Profile School_Profile { get; set; }
    }
}
