//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightHouseMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_Profile
    {
        public int Teacher_ID { get; set; }
        public string Picture { get; set; }
        public string Username { get; set; }
        public string Password_MD5 { get; set; }
        public string School_Name { get; set; }
        public string Email_ID { get; set; }
        public string NFC_Teacher_ID { get; set; }
        public int School_ID { get; set; }
        public string Subjects { get; set; }
        public string Results { get; set; }
    
        public virtual School_Profile School_Profile { get; set; }
    }
}
